Revert "Bring back the source of libgit2 as it is needed for the test suite Was failing with: thread 'main' panicked at 'called `Result::unwrap()` on an `Err`  value: Os { code: 2, kind: NotFound, message: "No such file or  directory" }', src/libcore/result.rs:999:5"
This reverts commit 7c18e6a231e6ba0275e3fe10b6ffb4580dae5e7c.