lv2-atom: mark tests as broken for now
Despite attempts to fix the issues in the tests, new one keeps popping
up after every fix. Below is the current batch of problems that
appeared.

We'll give up for now and wait for a new upstream release that includes
https://github.com/RustAudio/rust-lv2/commit/44aac000be49216ddd00f46aa7e8a05bde4a09f7
and then take another stab at it again, hopefully from a better starting
point.

```
error[E0463]: can't find crate for `lv2_core`
 --> tests/atom_integration.rs:2:1
  |
2 | extern crate lv2_core as core;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: cannot find derive macro `PortCollection` in this scope
  --> tests/atom_integration.rs:12:10
   |
12 | #[derive(PortCollection)]
   |          ^^^^^^^^^^^^^^ help: a derive macro with a similar name exists: `URIDCollection`
   |
  ::: /tmp/tmp.miTdL7LaxY/registry/urid-derive-0.1.1/src/lib.rs:11:1
   |
11 | pub fn urid_collection_derive(input: TokenStream) -> TokenStream {
   | ---------------------------------------------------------------- similarly named derive macro `URIDCollection` defined here

error: cannot find derive macro `FeatureCollection` in this scope
  --> tests/atom_integration.rs:18:10
   |
18 | #[derive(FeatureCollection)]
   |          ^^^^^^^^^^^^^^^^^

error: cannot find macro `lv2_descriptors` in this scope
  --> tests/atom_integration.rs:73:1
   |
73 | lv2_descriptors![AtomPlugin];
   | ^^^^^^^^^^^^^^^

error[E0412]: cannot find type `InputPort` in this scope
  --> tests/atom_integration.rs:14:12
   |
14 |     input: InputPort<AtomPort>,
   |            ^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `AtomPort` in this scope
  --> tests/atom_integration.rs:14:22
   |
14 |     input: InputPort<AtomPort>,
   |                      ^^^^^^^^ not found in this scope
   |
help: you might be missing a type parameter
   |
13 | struct Ports<AtomPort> {
   |             ++++++++++

error[E0412]: cannot find type `OutputPort` in this scope
  --> tests/atom_integration.rs:15:13
   |
15 |     output: OutputPort<AtomPort>,
   |             ^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `AtomPort` in this scope
  --> tests/atom_integration.rs:15:24
   |
15 |     output: OutputPort<AtomPort>,
   |                        ^^^^^^^^ not found in this scope
   |
help: you might be missing a type parameter
   |
13 | struct Ports<AtomPort> {
   |             ++++++++++

error[E0405]: cannot find trait `Plugin` in this scope
  --> tests/atom_integration.rs:34:6
   |
34 | impl Plugin for AtomPlugin {
   |      ^^^^^^ not found in this scope

error[E0412]: cannot find type `PluginInfo` in this scope
  --> tests/atom_integration.rs:39:27
   |
39 |     fn new(_plugin_info: &PluginInfo, features: &mut Features) -> Option<Self> {
   |                           ^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `lv2_descriptor` in this scope
   --> tests/atom_integration.rs:134:35
    |
134 |         let plugin_descriptor = &*lv2_descriptor(0);
    |                                   ^^^^^^^^^^^^^^ not found in this scope

Some errors have detailed explanations: E0405, E0412, E0425, E0463.
For more information about an error, try `rustc --explain E0405`.
error: could not compile `lv2-atom` due to 11 previous errors
```